##############
### 공통 
##############
# embeded tomcat
server:
  servlet:
    context-path: /demo-api
  tomcat:
    uri-encoding: UTF-8  
    
spring:
  profiles:
    active: local
  # APPLICATION SETTINGS (SpringApplication)
  main:
    show-banner: true    
  # favicon
  mvc.favicon.enabled: false  
  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8 # the encoding of HTTP requests/responses
      enabled: true # enable http encoding support
      force: true # force the configured encoding
  jackson:    
    serialization:      
      write-dates-as-timestamps: false
  session:
    store-type: none
      
logging:
  config: classpath:logback-spring.xml
  
---

##############
### local
##############

env:
  profile : local
  
  
# embeded tomcat
server:
  port: 8001
  
 
tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8019
  
    
spring:
  profiles: local
  
  multi-datasource:
    demo:
       #driverClassName: oracle.jdbc.OracleDriver
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://mariaburger.ceczqdx83uhe.ap-northeast-2.rds.amazonaws.com:3306/mariaburger?useSSL=false&serverTimezone=UTC
      username: root
      password: cococon123
      type: com.zaxxer.hikari.HikariDataSource     
      hikari:       
        connection-test-query: SELECT 1 FROM dual
        minimum-idle: 5
        maximum-pool-size: 10
        connection-timeout: 300000


logging:
  level:  
    com.example.demo: DEBUG   
    org.springframework: info
    org.mybatis: debug
    jdbc.sqlonly: OFF
    jdbc.sqltiming: DEBUG
    jdbc.audit: off
    jdbc.resultset: off  
    jdbc.resultsettable: debug
    jdbc.connection: off
    
   # - jdbc.sqlonly : SQL문만을 로그로 남기며, PreparedStatement일 경우 관련된 argument 값으로 대체된 SQL문이 보여진다.
   # - jdbc.sqltiming : SQL문과 해당 SQL을 실행시키는데 수행된 시간 정보(milliseconds)를 포함한다.
   # - jdbc.audit : ResultSet을 제외한 모든 JDBC 호출 정보를 로그로 남긴다. 많은 양의 로그가 생성되므로 특별히 JDBC 문제를 추적해야 할 필요가 있는 경우를 제외하고는 사용을 권장하지 않는다.
   # - jdbc.resultset : ResultSet을 포함한 모든 JDBC 호출 정보를 로그로 남기므로 매우 방대한 양의 로그가 생성된다.
   # - jdbc.resultsettable : SQL 결과 조회된 데이터의 table을 로그로 남긴다.
   
---

##############
### dev
##############


env:
  profile :  dev

# embeded tomcat
server:
  port: 8080
    
tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8009

spring:
  profiles: dev
  
  multi-datasource:
    demo:    
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://mariaburger.ceczqdx83uhe.ap-northeast-2.rds.amazonaws.com:3306/mariaburger?useSSL=false&serverTimezone=UTC
      username: root
      password: cococon123
      type: com.zaxxer.hikari.HikariDataSource     
      hikari:       
        connection-test-query: SELECT 1 FROM dual
        minimum-idle: 5
        maximum-pool-size: 10
        connection-timeout: 300000
    

logging:
  level:  
    com.example.demo: DEBUG   
    org.springframework: info
    org.mybatis: debug
    jdbc.sqlonly: OFF
    jdbc.sqltiming: DEBUG
    jdbc.audit: off
    jdbc.resultset: off  
    jdbc.resultsettable: debug
    jdbc.connection: off
  
---

  
logging:
  level:  
    com.example.demo: INFO
  
  
